### ISSUE TITLE
backend: Accept a diversity of GitHub URLs

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#125]
## Url Submission Examples
[Category 1] Currently, the only accepted forms of GitHub URLS are the following
* `https://github.com/<USERNAME>/<REPO_NAME>`
* `https://github.com/<USERNAME>/<REPO_NAME>.git`

[Category 2] However, this is also a common variant that students end up submitting for their REPO:
* `https://github.com/<USERNAME>/<REPO_NAME>/tree/main`
* `https://github.com/<USERNAME>/<REPO_NAME>?tab=readme-ov-file`

[Category 3] Or, they incorrectly post a link to a folder inside of the GitHub repository, like the following:
* `https://github.com/<USERNAME>/<REPO_NAME>/tree/main/0-chess-moves/starter-code/chess` (specific branch)
* `https://github.com/<USERNAME>/<REPO_NAME>/pull/1` (pull request instead)

## Issue
The urls in Category 2 really should be just as valid as those in category 1. They are still representing the same information, and a student is likely to end up grabbing this url. However, the autograder will fail.

## Proposal
Adapt the autograder to extract the url _only up to_ the name of the repository, and ignore all the trailing characters. This would simplify issues that really shouldn't exist for the students. 

It would also come with the side effect that students would be **quietly** disallowed from pointing the autograder at a specific branch (which they may attempt to do intentionally). Here are several solutions to this particular issue:
1. Display the _effective URL_ inside the autograder. A sharp student will be able to notice the difference and merge their code into `main`.
2. Specifically display a message when we use a normalized URL instead of the provided URL. Since they'll be using the same url all semester, and the point is to remove the need to update their submission inside Canvas, this may not be the recommended approach.

## Possible Implementation Note
This kind of cleanup could be performed while setting the `repoURL` param on a `Grader` object.

**Comment by frozenfrank** [comment]
@pawlh

**Comment by pawlh** [comment]
I like this approach. I am not a fan of people needing to resubmit the Canvas assignment multiple times, and I agree that this would provide an easily solution for most of the repo issues we experience this semester

**Comment by frozenfrank** [comment]
Be aware of #240 which allows admin users the ability to run any git URL they want through the autograder.

While working on this issue, we want to make sure that any string cleaning and stripping is:
1. Located in a nicely named and appropriately placed helper function, AND
2. Not performed on any manually entered URLs from the admin panel

Assuming that the autograder can load a particular branch when it's properly encoded in the url (this may need to be a separate issue), this would allow us to conveniently change which branch of code is evaluated just by changing the string we pass in. 

This approach would be disallowed if the string URL processing always happens, but it can be avoided by being intentional about the place we call the function from.
