### ISSUE TITLE
backend: use full datetime for due dates

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#126]
Currently the due date checker ignored the hour, minutes, and seconds. The canvas time should be canonical

**Comment by frozenfrank** [comment]
It seem like this issue was reopened by #161

**Comment by frozenfrank** [comment]
@pawlh Sorry that my code didn't compile correctly. Can you do one of the following to help me:
1. Help me set up the compiler so I can test it myself, OR
2. Show me the console output with the errors so that I can resolve it?

Sorry again for causing problems.

**Comment by frozenfrank** [comment]
Nvm. Michael helped me set up my environment properly, and now the errors are very obvious to me. 😬

**Comment by frozenfrank** [comment]
The solution to this issue should also solve the issue in #168. Upon request, I can split the solutions to the separate issues into separate pull requests as well.
