### ISSUE TITLE
frontend: Limit submission view to X most recent entries

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#149]
At this point, it's probably no longer necessary to view _all_ the submissions in the autograder.

Update the front end SQL statement to limit the number of results returned. Here is a guide on how to do that based on the type of database used: [SQL Select Limit — W3 Schools](https://www.w3schools.com/sql/sql_top.asp).

We'll need to choose that number X. The number 100 seems like a reasonable value, but 25 would be better if it's all that's required.

If there are any other use cases that do require access to older submissions than only the most recent X submissions should be created as separate issues to be completed independently. While I don't have enough information to know which other views of the data are required, a few ideas are listed here that may be helpful or necessary in creating additional issues:
* Introducing a pagination component that would allow us to paginate the results from the current table, or any of the proposed tables as well
* View recent submissions for a given phase
* View all submissions for a given student 
* General submission filtering: all submissions matching a provided phase ID within a given date range. We could potentially extend it to support querying by student section ID, professor, or other etc...

**Comment by DallinFromEarth** [comment]
#158 will be making the list of submissions filterable by Student name, phase, score, and date range. Once that is implemented, will this still need to be done?

**Comment by frozenfrank** [comment]
> #158 will be making the list of submissions filterable by Student name, phase, score, and date range. Once that is implemented, will this still need to be done?

@DallinFromEarth Yes, especially so. Currently, the "Submissions" tab is the default page that opens for a TA. Currently, it's downloading the entire set of all submissions, including all of their submission comments. This is unnecessary. While we may want to preserve the ability to query them all right now, it's no longer necessary.

Now, this "submissions" screen is useful for seeing the most recent few submissions (like 10), and then if we want to drill into a specific submission or search for a specific submission from a specific student, it will be much easier to use your new "Students" tab (#212).

If there still remains a need to search through all submissions, we should identify it and provide a more specialized method. For now, the only clear need to to confirm the status of a recent submission. Anything older than current things can be accessed in other ways.
