### ISSUE TITLE
backend: accept options for phase1 to enable/disable checks for the extra credit

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#15]

**Comment by frozenfrank** [comment]
@pawlh Why wouldn't we always look for the extra credit, and then remain silent if they don't pass? Asking the user to specify if they completed the extra credit doesn't seem like a required user flow.

**Comment by pawlh** [comment]
Yep, I totally agree with you here. My current plan is to implement extra
credit like this:

   - check for extra credit on the backend when grading Phase 1
   - add a boolean 'passed' field to the Submission model
      - this will only be set to true if the required tests pass, not if
      the score is >= 100%

I need to go through the issues and clean them up. Most of them were
written a little carelessly as I thought of new issues, but most of them
lack thorough descriptions and some should be gone

**Comment by frozenfrank** [comment]
@pawlh That makes sense. Thanks for providing that additional context.
