### ISSUE TITLE
backend: Create memory DAO's that allow us to skip MySQL for development

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#163]
When just trying to test front-end stuff, and I don't really need the SQL server. I should be able to run the server in `dev` mode that will use memory DAO's instead of the database DAOS. Ideally, it would also automatically populate the DAO's with some data that is helpful for having an environment.

This would be well accomplished by providing alternatives in the `DaoService` file that ends up using memory DAO's instead of Database DAO's.

**Comment by pawlh** [comment]
I absolutely agree with this one. You might have noticed that I have half-hearted support for a memory database already set up, but there is not currently an easy way to enable it.

This is something that has been on my todo, so thanks for bringing it closer to reality with this issue :)

**Comment by ThanGerlek** [comment]
Do we want to try to make this work with phases 4-6? I've created a dev branch with proposed implementations of the other two DAOs (including pulling rubric configs from a json file) (no actual injection yet though), which is enough for phases 0-3 as long as we only submit repos that are themselves set to use memory DAOs. Obviously not ideal but probably enough for any front-end testing.
