### ISSUE TITLE
Expected penalties are applied to grade after extra credit points are added

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#168]
## Overview
Adjust the calculation of final scores so that any late penalties (or other penalties applied for low commit frequency etc) are applied based on a percentage of the final score _after_ any extra credit points are accounted for.

The grade should be calculated as the following formula:
```
LATE_PERCENTAGE_PER_DAY = 10
LOW_COMMIT_PENALTY_PCT = 10

gradedScore = percentage_tests_passed + extra_extra_credit_points_available
latePenaltyModifier = 1 - (LATE_PERCENTAGE_PER_DAY/100 * effective_days_late)
lowCommitModifier = 1 - (commits_under_permissible_threshold ? 0 : LOW_COMMIT_PENALTY_PCT)
finalScore = gradedScore * latePenaltyModifier * lowCommitModifier

return finalScore;
```

## Discussion
Professor Jensen said the following:
> I would have expected penalties (late, git commits) to apply after calculating the final score.

This was said in response to the following TA discussion
> **TA 1:** Should the late penalty apply to the extra credit points? It looks like the autograder is not currently doing that. For example, a student got 78% turning it in 3 days late, rather than 75.6% I would expect if the late penalty applied to those points

> **TA 2:** Personally I don't think it should penalize the extra credit, although I'd agree that the syllabus wording isn't perfectly clear: "The late penalty for all assignments is 10% off per school day"

> **TA 3:** This [proposed adjustment] would also be consistent with the behavior for partial credit submissions which may occur on phase 6.

##  Test Cases
* A student passes all the tests and the extra credit tests for a total raw score of **108%**. However, the student turns in the code **one school day** late (10% per day). This results in a final score of **97.2%** 
* On a later phase, a student receives credit for **60%** of the points on the rubric. However, the student only committed on **2 days** instead of the 3 separate days required by #160. Therefore, a 10% penalty is applied for a total score of **54%**.
* A student passes all of the test cases, but turns in the code **8 school days** late. He is only penalized for the first 5 of these, so the final score if **50%**.

**Comment by frozenfrank** [comment]
Since #228 will have to deal with the commit penalty, we'll chose NOT to handle the commit penalty in this issue. Issue #228 will handle the penalty somewhere else.

**Comment by DallinFromEarth** [comment]
> * On a later phase, a student receives credit for **60%** of the points on the rubric. However, the student only committed on **2 days** instead of the 3 separate days required by [hold off submitting scores for low commit submissions #160](https://github.com/softwareconstruction240/autograder/issues/160). Therefore, a 10% penalty is applied for a total score of **54%**.

When we say a 10% penalty, are we talking 10% of the points earned, or 10 percentage points? I always thought it was 10 percentage points off, meaning that no matter what the student scored, the penalty would drop them 10 percentage points. (i.e. 100%->90%, 68.5%->58.5%, etc)

**Comment by frozenfrank** [comment]
@DallinFromEarth That actually makes a lot of sense. I think it's currently behaving as you described, but your description differs from what @leesjensen is quoted as saying in the original description. I think that @19mdavenport is moving forward with an adjustment that makes it behave as currently defined here. Are we all OK with that? 

Speak now, because Michael moves fast and gets stuff done :)

**Comment by DallinFromEarth** [comment]
> but your description differs from what @leesjensen is quoted as saying in the original description.

> Professor Jensen said the following:
> 
> I would have expected penalties (late, git commits) to apply after calculating the final score.

At least based on this quote, I'm not sure it's inherently different, though I definitely see where you're coming from. 

I'm good either way as long as the professors are happy. I do have some reservations about changing it:
- Changing how we calculate scores in the middle of the semester can cause some confusion for students
- If we're calculating where it's 10% of points earned, then we'll have to keep track of their late deduction, so we know what to base the git commit penalty on, which is calculated later (or at least had the possibility of being altered later)

**Comment by 19mdavenport** [comment]
Right now as far as late penalties go, it is multiplicative. It's 10% of the points earned, so 108% 5 days late is 54% instead of 58%. 60% points earned 1 day late would be 54% instead of 50%. 

I think that's generally kinder to low preforming students who at least turned something in. 60% 5 days late could be 30% or 10%

**Comment by frozenfrank** [comment]
> I think that's generally kinder to low preforming students who at least turned something in. 60% 5 days late could be 30% or 10%

This is true. It's harsher on high achieving students who may have finished the extra credit with a late penalty, but it's dramatically kinder to lower achieving students. I agree that this is overall a fairer scoring system.

> If we're calculating where it's 10% of points earned, then we'll have to keep track of their late deduction, so we know what to base the git commit penalty on, which is calculated later (or at least had the possibility of being altered later)

Based on this topic, I don't think anyone would complain if the "Git Commit" penalty were applied as a multiplication after any late penalty were already deducted. Besides being technically simpler for us to implement, it would also give the students a higher grade whenever both penalties would be applied together. For example:
1. Student A receives full credit but turns in the assignment 1 day late and doesn't meet the commit threshold. After going through the reserved process and the TA approves their submission, the final score would be **81%** `= 100% x (1 - 10%) x (1 - 10%)`. This is slightly higher than the **80%** `= 100% - 10% - 10%` that they would receive if we calculated the scores as before.
2. Student B receives 60% credit and turns in the assignment 5+ days late and doesn't meet the commit threshold. After the approval process, the final score would be **27%** `= 60% x (1 - 50%) x (1 - 10%)`. This is significantly higher than the **0%** `= 60% - 50% - 10%` score they would receive if we straight up subtracted 10% for each penalty, and slightly higher than the **24%** `= 60% * (1 - 50% - 10%)` score if we attempted to preserve the ratio.

Additionally, low-performing students who are already _way past the deadline_ are much less likely to miss the commit threshold. They have more time to commit and author commits.

I propose that the front-end **not** attempt to use the same multiplication factor, but that it freshly reduces the score by 10% per the math demonstrated above.

I think this new direction is sufficiently fair for all students and simple to implement.

What do you think about this @DallinFromEarth ?

**Comment by DallinFromEarth** [comment]
I think this seems like an excellent way to implement it, and does seem fairer to students. Especially considering the scenario of Student B you came up with. I agree with this proposal as long as the professors are cool with it.
