### ISSUE TITLE
only open one websocket per session

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#192]
Currently a websocket connection is opened for every Phase when any phase is submitted. This should be changed to work as follows:

- Upon initial loading of `cs240.click`, a connection is opened to `wss://cs240.click/ws` that will remain open for the duration of the user's visit
- Websocket messages from the server currently don't specify which phase they are for, but this should be changed to look something like this:
```json
{
   "phase": 1,
   "type": "update",
   "message": "Your code is in the oven"
}
```
- The frontend will only display messages on the tab that corresponds with the message's specified phase

**Comment by 19mdavenport** [comment]
@DallinFromEarth did the UI update you made resolve this?

**Comment by DallinFromEarth** [comment]
> @DallinFromEarth did the UI update you made resolve this?

I didn't explicitly go in and fix it, but I think my UI update should have had that effect. My understanding was the original problem came from there being multiple tabs, which is no longer the case
