### ISSUE TITLE
Make sure all* rubric items are independent of each other

### ISSUE THREAD

**Issue by ThanGerlek** [softwareconstruction240/autograder#211]
*With the following exceptions:
- Git commits: not worth points (from the autograder's perspective at least). Rejects submission, requires passing off with a TA
- Tests from previous phases (student tests, or just passoff?): not worth points. Rejects submission until fixed
- Extra credit / late penalties should apply after calculating the final score

**Comment by frozenfrank** [comment]
And just to be clear about the relationship with this item and #168, all the rubric items should be treated individually, but then any late penalties and other penalties should apply _only_ to the final score based on removing percentages from the sum of all the rubric items. Is that correct @ThanGerlek @pawlh ?

**Comment by ThanGerlek** [comment]
Good point--that's my understanding, yes

**Comment by frozenfrank** [comment]
@ThanGerlek Thanks for submitting this issue. I'm still a little confused on the issue occurring though I see you've detailed the exceptions.

What is going on that makes the rubric items not independent of each other, or how can you tell that there is an issue here?

**Comment by 19mdavenport** [comment]
As far as I'm aware, yes. I think this was mostly about unit tests not being required for passing off. I'm going to close this, but if anyone thinks there are still problems with this, please reopen it.
