### ISSUE TITLE
Frontend: Allow a TA to submit a previously unapproved submission to Canvas

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#228]
This is an extension of #160. That issue blocks submissions from being approved based on their commit status, but then a TA is required to manually approve the submission, likely but optionally, with a 10% penalty for not following procedure. 

Not only is this poor, unsuspecting TA required to perform the math to make the penalty, but then they also have to locate the student in Canvas to enter the grade.

Ideally, the TA would be able to hit an "Approve submission" or an "Approve without penalty" button that hits a new endpoint on the server to submit the grade directly into canvas.

**Comment by frozenfrank** [comment]
This could be a good issue for @DallinFromEarth

**Comment by DallinFromEarth** [comment]
> This could be a good issue for @DallinFromEarth

I would love to take this issue on once we get a better idea of where #160 is going

**Comment by frozenfrank** [comment]
> I would love to take this issue on once we get a better idea of where #160 is going

I can provide some information on that issue that may allow you to start on this one.

## What we know
While there are some technical details still being sorted out, we do know the following:
1. Sometimes, students will submit code that doesn't pass the commit requirements
2. In these cases, the autograder will still run and produce a `Submission`
3. In these cases, the autograder will withhold the student's grade for the phase and **not** submit it to canvas
4. The autograder will refuse to send a grade to Canvas for any further submissions on this phase
5. Students will need to talk to a TA to receive a score
6. The TA will usually deduct a 10% penalty from the final score (per #168 this penalty would already be accounted for in the grade saved in the `Submission`).
7. The TA can choose to add back the 10% penalty if they feel the student is learning their lesson about committing
8. The TA will be responsible for sending the final grade to Canvas

This issue is concerned with number 6-8 of the process.

## What this issue would do
1. Detect when a submission score was not sent to Canvas
    - This will probably require a special field to indicate this status
    - We'll want to make sure this works in all places where submissions are rendered (Submissions List & Student Submissions right now)
2. Provide a UI for a TA to approve the score and send it to canvas
    - Also provide a mechanism for the TA to add back the 10% penalty before sending it
3. Provide a server side endpoint that will fulfill the request
    - It should send the grade to Canvas and include a note indicating that the score was approved.
    - The comment should include the name of the TA approving the grade

That's it! That's all this would need to do!

The only question mark for this issue then is the detection of submissions where the grade wasn't sent. That could be easily skipped for now by referencing a method called `boolean Submission.pendingApproval()` which may default to `true` (and be available for all submissions) for now, but which can be easily replaced with corrected functionality.

**Comment by frozenfrank** [comment]
@DallinFromEarth Here is some more relevant information:

It appears that the Phase 5 rubric has an entry for "Git Commits," defined out of zero points. We'll still need to calculate the total score, but it looks like you have a specific field for storing the penalty as a negative number in that field.

<img width="335" alt="image" src="https://github.com/softwareconstruction240/autograder/assets/19808440/7b28a346-c5ec-4b47-b5f3-8a36694fed98">

Note that this is very convenient for the purposes of the Git commits, but it would be really nice to have a rubric item for the late penalties as well. I'll create a new issue to represent this.
