### ISSUE TITLE
admin: run arbitrary GitHub repo through grader as test

### ISSUE THREAD

**Issue by DallinFromEarth** [softwareconstruction240/autograder#240]
Instead of having to change the test student's gitHub repo assignment every time a TA wants to run a repo through the autograder (either for their own practice, debugging, or working with a student) it would be nice if we could just run a repo through the admin panel

**Comment by DallinFromEarth** [comment]
This commented out code has been living in SubmissionController for a long time. I don't know who left it here, but I'm going to take it out until its decided what to do about it

```
// FIXME: improve git url validation
// if (!request.repoUrl().matches("^https://[\\w.]+.\\w+/[\\w\\D]+/[\\w-/]+.git$")) {
//     halt(400, "That doesn't look like a valid git url");
//     return;
// }
```

**Comment by frozenfrank** [comment]
@DallinFromEarth I love this move! If we need it again, we can always get it out of `git` again.
