### ISSUE TITLE
admin: better "failed to package repo" error details

### ISSUE THREAD

**Issue by DallinFromEarth** [softwareconstruction240/autograder#255]
## The Problem
Often time students reach out or join the help queue because they get a `Failed to package repo` error on the autograder. These issues are difficult to diagnose from a distance. The current solution is to clone the repo to your own machine, and run maven build to see the build issues that result in the `Failed to package repo` error.

## Potential Solution
1) Add a tool either in the submissions tab or elsewhere that allows you to run `maven build` on a repo at will and see the errors you would see running on the command line.

and or:

2) forward maven compiling errors to the user when they receive the error, so they don't need to go to the TA for this help

**Comment by 19mdavenport** [comment]
Is #257 not sufficient for this?

**Comment by pawlh** [comment]
> Is [#257](https://github.com/softwareconstruction240/autograder/pull/257) not sufficient for this?

@DallinFromEarth I'm thinking that #257 covers this. Are you good with that?
