### ISSUE TITLE
Backend: Specifically Code to check for Common Issues and Provide Helpful Error Messages

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#266]
## Overview
Students frequently have problems while using the autograder and ask the TA's for help. A large majority of the time, the problems are based on a small set of simple issues that students miss in the specs or glaze over the exact details, which matter. The students then complain on the Slack or to the TA's basically the following "The tests pass on my local machine, but they fail on the autograder." Right now, the autograder doesn't give them the clues they would need in order to debug these issues for themselves.

## Potential Solution
We could write code to detect these common issues and provide more helpful error messages. This would make the students happier by enabling them to solve their own problems, and also reduce the load on TAs to identify and solve these common issues.

### List of Common Errors
| Affected Phase | Root Cause | Sub-Issue |
|:------:|--------|--------|
| All | Modified test files | #361 |
| All | Incorrect Test location | #362 |
| 4 | (Windows exclusive) Table name case sensitivity issues | #363 |
| All | "Failed to Package Repo": Using extra imports | #364 |
| All | "Failed to Package Repo": Bad structure | #365 |
| All | "Failed to Package Repo": Inappropriate dependencies between modules | #366 |

## Implementation Tips
This will require:
1. Adding support for inserting arbitrary checks and hints of the source code
2. Provide hooks to implement some of these checks and more in the future
3. Implementing the sub-issues individually

Since separate issues have been created to track each of the specific checks, this issue is primarily concerned with the setup and organization of tools that will enable the sub-issues to be implemented. A PR that closes this issue may also close one or more of the sub-issues. Future PR's may close multiple of the sub-issues at a time; this is especially likely in cases where the sub-issues are closely related, and one set of code can easily be configured to scan for multiple kinds of errors.

Some of the sub-issues will require further discussion and ideation. We may need additional support from additional individuals to figure out how to solve some of them reliably, and some of them may not be consistent enough for us to reasonably detect the issue with high confidence. In those cases, individual sub-issues can be closed independent of the other sub-issues that will continue.

## Credits
Co-authored by: @pawlh & @prattnj & @19mdavenport

**Comment by frozenfrank** [comment]
While digging through the `git show` man pages, I found the following options that could help us with comparing test files to the given files.

Notice that these options allow us to ignore whitespace (and line endings) to just detect differences in the actual code!

```bash
> git show --help

       --ignore-space-at-eol
           Ignore changes in whitespace at EOL.

       -b, --ignore-space-change
           Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all other sequences of one or more whitespace characters to be
           equivalent.

       -w, --ignore-all-space
           Ignore whitespace when comparing lines. This ignores differences even if one line has whitespace where the other line has none.

       --ignore-blank-lines
           Ignore changes whose lines are all blank.
```

**Comment by 19mdavenport** [comment]
Closing this as there is only 1 remaining
