### ISSUE TITLE
Backend: Convert DataAccessException into a named Exception instead of a RuntimeException

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#267]
I hope the title is explanatory enough. I assume that `DataAccessException` was defined as a subclass of `RuntimeException` for ease of migration, but we really want it to be a named exception that must be declared.

This will require changing the definition, and then updating any instances in the code to explicitly or catch the exception wherever it occurs. It is unknown how many places this will be needed.

The definition of the exception in in file `src/main/java/edu/byu/cs/dataAccess/DataAccessException.java`.

**Comment by 19mdavenport** [comment]
![image](https://github.com/softwareconstruction240/autograder/assets/52420978/87ed2a82-0751-4215-84f1-4e2d149281a6)

**Comment by frozenfrank** [comment]
@19mdavenport @pawlh It looks like I was confused when I wrote this issue. I meant to indicate the `DataAccessException.

Is the `DataAccessException` supposed to extend `RuntimeException`?

See the file: `src/main/java/edu/byu/cs/dataAccess/DataAccessException.java`

**Comment by 19mdavenport** [comment]
Oh that makes sense
