### ISSUE TITLE
Backend: Streamline SQL DAO column list management

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#281]
This process was already begun in commit ec4cd004c08557e08b3ffd41085035e32a19c2a5 of #233 in the Submission DAO. We'll want to finish dynamically generating the proper number of question marks for the insert command.

We'll also want to apply the same techniques to the other DAO's so that they are all on the same page.

**Comment by ThanGerlek** [comment]
How do you propose we do this? Or rather, what's the goal? Parsing the number of question marks from the ALL_COLUMN_NAMES string feels pretty unstable, and to make it _completely_ dynamic, we would need a file or an array that manually tracks the names, types, and `Submission` getters of every column, which seems unnecessary.
