### ISSUE TITLE
backend: Scorer#getScore only considers some of the important portions of the score

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#353]
The method currently looks at the passoffTests, regular tests, and quality score, but it ignores any scoring from the git commits. 

Adding GitCommits to the Rubric Item may address this issue, but are there any other places that also need adjustments with new rubric items?

Currently, in all the contexts this method is used, it doesn't matter. However, this is the kind of issue that would cause logical issues in the future if it isn't identified. See [this line](https://github.com/softwareconstruction240/autograder/pull/351/files#diff-b9cb335058e9da0451c7805989ff402b8b6ab22f98c041a491855c2d1ca2acddR271) for the currently identified issue.

This relates to, and would likely be solved by, whatever solves #300.

**Comment by 19mdavenport** [comment]
Resolved by #352
