### ISSUE TITLE
Fullstack: Accept student GitHub URL's from AutoGrader

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#409]
## Issue
Currently, for the initial "Chess GitHub Repository" assignment, students must submit information in two different places:
1. Submit GitHub URL to Canvas (to identify the student's repo)
2. Click the button on the AutoGrader to evaluate it and receive points

Currently, this requirement is documented in the ["Deliverables"](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/chess-github-repository/chess-github-repository.md#-deliverable) section of the assignment spec.

We've noticed that in the Fall 2024 semester, a significant portion of students (as many as 16 of 51; 31%) have been submitting the url to Canvas but not requesting the grade from the autograder. This leads to TA's sending individual messages to the students who haven't fully submitted, and student's feeling confused when they think they've finished the assignment, but it's not yet fully done.

Is there a better way to do it?

## Proposal
Adjust the autograder to accept and require the GitHub URL from students before handling autograding requests.

### GitHub URL Acceptance Specifics
The GitHub URL should be sent to Canvas for now to remain compatible with our current system. However, in the future, we may choose to keep it fully internal to the AutoGrader and only send grades to Canvas. 

We should provide basic validation that the URL is a GITHUB url before accepting it into our system. 

This would also be a good opportunity to perform a repository claim check so that a student cannot claim a repo already in use (this would be an improvement upon #69).

**Consider: Do we want to allow students to edit their GitHub URL?** This would be helpful if students accidentally provide an incorrect URL, but this can be minimized with URL validation and repository claim validation. However, we may not want to allow that kind of behavior since it could lead to increased cheating. Firstly, the commit verification system may always produce failing results if there is no shared history with a previous submission. Secondly, this may only provide students the opportunity to claim work they didn't set out to claim as theirs in the beginning of the semester.

### Potential Front End Implementations

Below are two ideas for ways this could be implemented. Please comment with your vote and provide additional insight or alternative implementation ideas. We could move forward with any one, or a combination of these ideas mixed with new ideas.

#### Proposal 1: Onboarding Flow
Craft an introductory "onboarding flow" into the autograder that requires a GitHub URL from the student before proceeding to the main page. This page would block students from seeing the rest of the information in the autograder until they have a GitHub URL saved. In the future, we may add additional steps in the flow to provide helpful information or to ask additional questions.

##### Pros
* Obviously asserts the information we need
* Lays foundation for future onboarding/required questions
* Matches onboarding pattern common in the tech community

##### Cons
* Does not allow for easy resubmissions/edit of URL

#### Proposal 2: Dedicated GitHub URL page
We could add the GitHub URL input to the "GitHub Repository" page and make students perform two actions on that same page:
1. Provide the URL
2. Request to grade 

Future "phase" pages should be disabled or hidden if no valid GitHub URL is provided. If a valid URL is provided, we could consider hiding the page, but it may be helpful to be able to resubmit/edit the URL. 

##### Pros
* Easily allows students to adjust their GitHub URL
* Page format is parallel to the behavior required for other phases

##### Cons
* Some may view a new page for this single setting unnecessary
* Students would need to submit on two different tabs within the AutoGrader

#### Proposal 3: Include GitHub URL in another place in the app

Alternatively, the textbox could be placed in a sidebar or some other menu along with other settings. This would be more complicated to find the first time, but could represent a good place to go change/view the setting later on in the semester.

##### Pros
* Provides natural place to hunt down (and change?) the GitHub URL in the future
* Minimizes changes to the required flow/pages of the app

##### Cons
* Could be difficult to find or left undiscovered by most students
* Would be used less than any other approach

**Comment by frozenfrank** [comment]
@DallinFromEarth @19mdavenport While the backend portion basically explains itself, which of the three proposals should we move forward with for the front-end portion?

**Comment by DallinFromEarth** [comment]
@19mdavenport and I spent a good chunk of time discussing this in person yesterday and trying to figure out the necessary backend flows and how the students would interact with the system. What we decided was essentially a blend of proposal 1 and 3. Here's the theory:

### Student Flow

**Initial Login & Onboarding**
The first time a student logs into the autograder, they will be presented with a new "RegisterView" which basically just asks them for their GitHub URL. That will get logged in the database in the student table as it is currently done. 

**Later Changes**
Once a student has been registered, there will simply be a button at the top of the autograder, basically where their repo url is currently displayed. That button will allow them to change the URL at anytime, and be easy to find.

### Backend System Flow

This will require some changes to the way logins are processed. The overview of the new process @19mdavenport and I discussed and I plan on implementing are thus (its based heavily on the current flow):

- Student clicks log in, triggering a call to BYU CAS
- CAS provides the netID of the student to the backend
- Backend checks the database to see if they exist yet
  - _If they do not exist:_ Backend queries Canvas, verifying the student is in the class
    - Backend will prompt frontend to show RegisterView and get the student's repoURL
    - Backend will clean and verify repoURL, and check it is not a duplicate
    - Backend then creates a new entry in the student table with the student's netID, canvasID, and repo
- Student is now authenticated 

### Concerns with allowing students to change RepoURLs
@19mdavenport brought up honor code concerns with allowing students to change their repoURLs at will. For example, without safeguards, a student could submit their code for a phase, change their repoURL to something else, then let their friend submit the same repo. There are a couple options for dealing with this that we discussed:

1. Do nothing, and allow students to change whenever they want. This is already technically a possibility under the current system with submitting changes through Canvas. 
2. Limit changing of repoURLs to admins only, requiring students to contact the TAs to change their repo.
3. Keep a log of repoURL changes

Personally, I think we should go with option 3. It allows the students the most flexibility, while also providing checks against cheating. (_And honestly it sounds like a fun project for me to tackle_) Although, it does add some complexity to the program, requiring a new table in the database and some additional checks on GitHub repos. If we decide we don't want this additional complexity, I'd recommend option 1, as I think it would be best to let students change their repos anyways, as is the current case.

**Comment by frozenfrank** [comment]
An extract from a Slack thread:
> **TA:** If we can require a valid url to register, would you be in favor of deleting the assignment?
> **@leesjensen:** Absolutely. No worries about it for now. Just something to think about for the future.

**Comment by 19mdavenport** [comment]
Proposal 4: A mix between 1 & 3
Another place in the app that students can access after registering but are required to use before accessing anything else.

**Comment by DallinFromEarth** [comment]
A status update and a followup to the discussion about which proposal to take: 

My work on branch `github-repo-improvements` for this issue as currently implemented proposal 1. Students can change their repo URL whenever they want. (They are required to provide a valid repo URL on their first login) Work is almost done to allow admins to edit a student's repo URL. 

Soon, I will implement a system to add the functionality for proposal 3 that will log each time a student changes their URL It ensures that submitted repo URLs aren't currently claimed by anyone else, and allows us to block them if the URL has ever has been claimed. 

_We should definitely ask the professors if they want students to be blocked from claiming URLs previously claimed by other students, or just currently claimed URLs_
