### ISSUE TITLE
Backend: Grafana logs should never clear

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#421]
Today, while looking into an issue, we found that the Grafana logs had been cleared from the autograder. This removed necessary debugging information.

**Comment by 19mdavenport** [comment]
Turns out, they didn't actually clear. I restarted Loki and they're back
https://github.com/grafana/loki/issues/13135
A simple version upgrade will likely fix this but I'll have to test to make sure that doesn't break anything else
