### ISSUE TITLE
Fullstack: Enhance late penalty applied presentation experience

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#430]
While discussing potential resolutions to #428, @19mdavenport and I discussed an improved student experience that shows their original score on each rubric item along with the actual score, adjusted for late penalties etc.

We decided that storing a single version of the `Submission` is prudent, and that we would want to use new fields in the `RubricItem` record to track the `rawScore` before penalties are applied. This maintains the original status of the `score` fields as consistent with the actual score that will be sent to Canvas.

When presenting the information in the UI, when the scores are different, we can show the raw score (100%), and note the adjusted score just below. Including a textual comment in the `notes` field or other flag field would be an option if we wanted to very clearly communicate exactly _why_ the points were deducted.

A resolution to this issue should also clear up any remaining unintended artifacts from #429.

**Comment by 19mdavenport** [comment]
@frozenfrank I saw you assigned this to yourself. Is it your intention to complete this? I was intending to do this but if you want to, I'm happy to leave it to you.

**Comment by frozenfrank** [comment]
@19mdavenport Have at it! I'm still working on a few other PR's.
