### ISSUE TITLE
Remove temp code for migrating urls to submission update table

### ISSUE THREAD

**Issue by DallinFromEarth** [softwareconstruction240/autograder#446]
When we moved GitHub Repo URL management to the autograder, some temporary code was added to the `UserController`. Now that the code has gone live and run, we no longer need that code.

_see the comment describing the code in https://github.com/softwareconstruction240/autograder/issues/425#issuecomment-2361439047_

**Comment by DallinFromEarth** [comment]
whoops, I already made an issue for this #434

**Comment by frozenfrank** [comment]
Duplicate of #434.

Using the [special syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/marking-issues-or-pull-requests-as-a-duplicate) enables additional GitHub features for duplicates.

**Comment by DallinFromEarth** [comment]
Ahhhhhh, that's actually really cool. Good to know for the future
