### ISSUE TITLE
Docs: Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#448]
## Overview
GitHub specially treats the [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file. We should leverage this behavior to help future people contribute to the project.

## Details to Include
Important notes to include:
* In this project, we approve typically PRs and allow the original submitter to press the merge button.
* New features and functionality must have tests demonstrating correctness.
* New contributors can begin by writing new tests for existing functionality to become acquainted with the code
* New contributors should start by reviewing our Sequence Diagrams (coming soon!)
* Potentially move (or link or extract) the getting started information into a separate document
    * Should this be a separate issue?
* Established conventions to naming issues
* Using the established Project
* Define a style guide
    * Small packages
    * SOLID principles
    * Standard naming conventions

## Other Examples
* [cezaraugusto](https://github.com/cezaraugusto/github-template-guidelines/blob/master/.github/CONTRIBUTING.md)
* See the [GitHub community checklist](https://github.com/softwareconstruction240/autograder/community) for more information.

## Places to Update
- [ ] Getting started guide ([comment](https://github.com/softwareconstruction240/autograder/blob/b7bdade400b8ac8d40c688a5d78192f7b58092c1/README.md?plain=1#L61-L62))

## Other Ideas
What other things should we include in the document?

**Comment by webecke** [comment]
You mention that new features should have tests. Do we run our test cases currently before deployment? If not, can we set a GitHub action that runs all the test cases before you're allowed to merge a pull request, in the same way we check it compiles and has valid type-checking? @frozenfrank @19mdavenport

**Comment by frozenfrank** [comment]
> You mention that new features should have tests. Do we run our test cases currently before deployment? If not, can we set a GitHub action that runs all the test cases before you're allowed to merge a pull request, in the same way we check it compiles and has valid type-checking? @frozenfrank @19mdavenport

**Yes!**

## Current Setup
We already have a [GitHub Actions](https://github.com/softwareconstruction240/autograder/actions/workflows/tests.yml) workflow that runs on every push (on every branch) and reports whether [all the test pass](https://github.com/softwareconstruction240/autograder/tree/main/src/test/java/edu/byu/cs) or not. This currently runs two checks:
* Do all of the tests pass?
* Does the Vue Linter report any issues?

We also have [another action](https://github.com/softwareconstruction240/autograder/actions/workflows/integration-tests.yml) set up that runs only when code is pushed to the `main` branch which runs the [Integration tests](https://github.com/softwareconstruction240/autograder/tree/main/src/test/java/integration). Based on the most recent commit message in that folder, it appears that the `CanvasIntegrationTest` has been disabled recently...

The point is that we do have the infrastructure in place to evaluate tests and ensure we have high-quality code!

## Where can you find it?
You may have noticed the green checkmarks— or red Xs— indicating the status of these "Actions" (screenshots). Notice that these marks are replaced with a yellow dot while the checks are currently running.
1. When a PR is merged
![image](https://github.com/user-attachments/assets/6ec838a8-a24f-4e23-8e1c-dce1c1905f8b)

2. Attached to any commit that _was_ the head of the branch when a branch was pushed
![image](https://github.com/user-attachments/assets/9d6674fe-1b88-4e2d-b7d3-90d1d527e63a)

3. In the browser tab favicon image
![image](https://github.com/user-attachments/assets/03e3a549-1441-4cc6-afef-d072ad6fa1e4)

4. On the PR page
![image](https://github.com/user-attachments/assets/bb3bdf21-a063-40bb-98aa-a825f16e5972)

5. And surely in many other places!

## Usefulness Example
In #423, I pushed my code and requested a review on the PR. However, I then received an email that I had failed the tests! I was able to look and find where I had made the mistake in the code in order to correct it. This history is all presented and displayed within the Pull Request page:

![image](https://github.com/user-attachments/assets/90211385-a8a2-4517-8418-784b5ff6e171)
