### ISSUE TITLE
frontend: improve user experience

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#73]
Early on I decided to put off mobile support in favor of faster development for the desktop.

There doesn't need to be perfect mobile support, but currently the site is essentially unusable

**Comment by DallinFromEarth** [comment]
I'll take this on, but expand this into include improvements to the whole user experience.

Things I'm thinking about incorporating and working on in this update:
- Simplified UI
  - Using flex display for responsive UI
- Dark Mode
- Reusable components for easier frontend development in the future
- Font Awesome Icons
- Links to the specs and help queue (Mostly a quality of life thing)
- Some sort of front-end config file
  - To allow for easy changing of external links, reused text, and deployment settings

This update will mainly focus on the student's front end, especially making it mobile friendly and responsive. And I acknowledge I might be overconfident right now looking at this, and some of these things might have to be pushed off to later updates. But this is my goal for now until I hit a brick wall or someone tells me no.
