### ISSUE TITLE
frontend: add logout option

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#90]

**Comment by DallinFromEarth** [comment]
when running locally, the /auth/logout route just goes to a blank home view, where trying it on the live takes you to a white screen that says "you are logged out". Not sure why its doing that

**Comment by pawlh** [comment]
> when running locally, the /auth/logout route just goes to a blank home view, where trying it on the live takes you to a white screen that says "you are logged out". Not sure why its doing that

As add odd as this seems, this is actually excepted behavior. On production everything runs from the same port (cs240.click:443) but locally in development you have the option to split the frontend and backend to be on different ports (localhost:5173 and localhost:8080 respectively). `/auth/logout` is a GET endpoint on the server, so if you try to visit `localhost:8173/auth/logout` then the default behavior is to show you the 404 route, which doesn't currently exist.

This would never happen on production because the frontend dev server is not being used, instead we are serving it statically with the server

**Comment by DallinFromEarth** [comment]
Change logout endput to a post
let front end handle redirection
set useAuthStore().user = null when you log out
await router.push({name: 'login'})

**Comment by DallinFromEarth** [comment]
the branch now functions without any issues. the logout link has the same functionality as the old /auth/logout method. It does not log you out of CAS though.
