### ISSUE TITLE
backend: investigate why queue can stop progressing

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#99]

**Comment by frozenfrank** [comment]
@pawlh Did we sufficiently solve this issue tonight, or do you feel we should keep investigating it?

For reference, we did create the following (related) new issues as a result of our investigations:
* #140 
* #142

Also note that we fixed two issues already:
* `synchronized` access to `notifySubscribers()`
* `Process.waitFor()` timeout after 30 seconds of hanging processing
